### ISSUE TITLE
위지윅에 적용한 폰트 사이즈가 마크다운 탭변경시 유지되지 않는 현상

### ISSUE THREAD

**Issue by exit11** [paerck25/tui-editor-plugin-font-size#7]
덕분에 폰트 사이즈 기능을 편리하게 사용을하고 있습니다.

@toast-ui/editor 3.2.0 버전을 사용을 하고 있는데,
위지윅에 적용한 폰트사이즈를 탭으로 마크다운 변경했을때, 적용된 사항이 사라지는 현상이 있습니다...
위 사항이 베이스로 사용하신 컬러피커에서는 정상작동을 하고 있습니다.
마크다운에서 적용 한 상태에서는 정상적으로 구현이 되고 있습니다.

**Comment by paerck25** [comment]
@exit11 
수정되었습니다 !! 이슈 제보 감사합니다!!
